language: ruby
rvm:
  - 2.4
  - 2.3
  - 2.2
  - jruby

sudo: false
cache: bundler

script: bundle exec rspec spec

notifications:
  email:
  - evo@zenexity.com

addons:
  code_climate:
    repo_token: f46a7e216896abddbc4877ce065239e8ac9f575af7a120bdaa61a42be70777e9

deploy:
  provider: rubygems
  api_key:
    secure: TBCtAi8FnlHzuiv86Me/YpMdGeAiG9d+J3ZpxWIY32jJv+t8dsW8Fej4jhGSW0aarPT7sarXan6cez0ssSDObUwWMYJfshmMsKykTi6TW4US2ZXtWxtglABYK2DJ/8N1fgkdXKO0NRMF7RVUoJNSw+91GX7ug/obNiCcmG/ms5I=
  gemspec: prismic.gemspec
  on:
    tags: true
    all_branches: true
